timeout: 10
triggers:
  - name: merge-request
    type: github_pr
    runs:
      - name: unit-test
        container: python:3.6-alpine
        host-tag: amd64
        script: unit-test
        shared-volumes:
          lmp-bitbake-cache: /lmp-bitbake-cache

      - name: flake8
        container: python:3.6-alpine
        host-tag: amd64
        script: flake8

      - name: test-progress
        container: python:3.6-alpine
        host-tag: amd64
        script: dumb-progress
        console-progress:
          progress-pattern: "\\nNOTE: Running task (?P<current>\\d+) of (?P<total>\\d+)"

  - name: build-container
    type: git_poller
    params:
      GIT_URL: "https://github.com/foundriesio/jobserv.git"
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: build-container
        container: docker:dind
        privileged: true
        host-tag: amd64
        script: build-container

  # This run is just handy for demonstration purposes as documented in the
  # tutorial
  - name: post-merge
    type: git_poller
    params:
      GIT_URL: "https://github.com/foundriesio/jobserv.git"
      GIT_POLL_REFS: "refs/heads/master"
    runs:
      - name: flake8
        container: python:3.5-alpine
        host-tag: amd64
        script: flake8

scripts:
  dumb-progress: |
    #!/bin/sh -ex
    sleep 10s
    echo "NOTE: Running task 1 of 12"
    sleep 10s
    echo "NOTE: Running task 2 of 12"
    sleep 10s
    echo "NOTE: Running task 3 of 12"
    sleep 10s
    echo "NOTE: Running task 4 of 12"
    sleep 10s
    echo "NOTE: Running task 5 of 12"
    sleep 10s
    echo "NOTE: Running task 6 of 12"
    sleep 10s
    echo "NOTE: Running task 7 of 12"
    sleep 10s
    echo "NOTE: Running task 8 of 12"
    sleep 10s
    echo "NOTE: Running task 9 of 12"
    sleep 10s
    echo "NOTE: Running task 10 of 12"

  flake8: |
    #!/bin/sh -ex
    pip3 install flake8 flake8-junit-report==2.1.0
    flake8 --ignore=E722,W605,E126 --exclude=migrations/ ./ | tee flake8.txt
    flake8_junit flake8.txt /archive/junit.xml

  unit-test: |
    #!/bin/sh -ex
    apk --no-cache add git python3-dev musl-dev gcc openssl libffi-dev openssl-dev
    git config --global user.email "cibot@example.com"
    git config --global user.name "cibot"

    ls /lmp-bitbake-cache/
    sh ./unit-test.sh

  build-container: |
    #!/bin/sh -e
    TAG=${GIT_SHA:0:6}

    unset DOCKER_HOST
    DOCKER_TLS_CERTDIR= /usr/local/bin/dockerd-entrypoint.sh --raw-logs >/archive/dockerd.log 2>&1 &
    for i in `seq 12` ; do
        sleep 1
        docker info >/dev/null 2>&1 && break
        if [ $i = 12 ] ; then
            echo Timed out trying to connect to internal docker host
            exit 1
        fi
    done

    set -x
    docker build -t doanac/jobserv:$TAG --force-rm .
    docker tag doanac/jobserv:$TAG doanac/jobserv:latest

    if [ -f /secrets/dockerpass ] ; then
        set +x
        token=$(cat /secrets/dockerpass)
        mkdir -p $HOME/.docker
        docker login --username=doanac --password=$token
        set -x
        docker push doanac/jobserv:$TAG
        docker push doanac/jobserv:latest
    else
        echo "dockerpass not provided, skipping publishing step"
    fi
