"""empty message

Revision ID: 3de1dc6abf74
Revises: 25403b01a59a
Create Date: 2019-10-30 09:52:31.931443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de1dc6abf74'
down_revision = '25403b01a59a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('synchronous_builds', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'synchronous_builds')
    # ### end Alembic commands ###
