"""empty message

Revision ID: d3094c0b3c83
Revises: f775fa543080
Create Date: 2018-06-05 16:03:39.422711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3094c0b3c83'
down_revision = 'f775fa543080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('deleted', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'deleted')
    # ### end Alembic commands ###
