"""empty message

Revision ID: ec74501d7086
Revises: 3c1cd792f312
Create Date: 2018-12-05 21:37:53.394055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec74501d7086'
down_revision = '3c1cd792f312'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_results', sa.Column('output', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_results', 'output')
    # ### end Alembic commands ###
