"""empty message

Revision ID: f775fa543080
Revises: f7ae9cf553c7
Create Date: 2018-02-15 09:15:12.933254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f775fa543080'
down_revision = 'f7ae9cf553c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('builds', sa.Column('trigger_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('builds', 'trigger_name')
    # ### end Alembic commands ###
